resource_types:
- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest

- name: s3-iam
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: s3-resource
    aws_region: us-gov-west-1
    tag: latest

- name: bosh-deployment
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: bosh-deployment-resource
    aws_region: us-gov-west-1
    tag: latest

- name: slack-notification
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: slack-notification-resource
    aws_region: us-gov-west-1
    tag: latest

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest

- name: bosh-io-stemcell
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: bosh-io-stemcell-resource
    aws_region: us-gov-west-1
    tag: latest

- name: bosh-io-release
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: bosh-io-release-resource
    aws_region: us-gov-west-1
    tag: latest

resources:
- name: uaa-config
  type: git
  source:
    commit_verification_keys: ((cloud-gov-pgp-keys))
    uri: ((uaa-config-git-uri))
    branch: ((uaa-config-git-branch))

- name: pipeline-tasks
  type: git
  source:
    commit_verification_keys: ((cloud-gov-pgp-keys))
    uri: ((pipeline-tasks-git-uri))
    branch: ((pipeline-tasks-git-branch))

- name: terraform-yaml
  type: s3-iam
  source:
    bucket: ((tf-state-bucket))
    versioned_file: ((tf-state-file))
    region_name: ((aws-region))

- name: common
  type: s3-iam
  source:
    bucket: ((secrets-bucket))
    versioned_file: opsuaa.yml
    region_name: ((aws-region))

- name: stemcell-jammy
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-jammy-go_agent

- name: uaa-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/uaa-release

- name: uaa-customized-release
  type: s3-iam
  source:
    bucket: ((bosh-releases-bucket))
    regexp: uaa-customized-(.*).tgz
    region_name: ((aws-region))

- name: secureproxy-release
  type: s3-iam
  source:
    bucket: ((bosh-releases-bucket))
    regexp: secureproxy-(.*).tgz
    region_name: ((aws-region))

- name: uaa-deployment
  type: bosh-deployment
  source:
    target: ((bosh-target))
    client: ((bosh-client))
    client_secret: ((bosh-client-secret))
    ca_cert: ((ca-cert))
    deployment: opsuaa

- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))

jobs:
- name: deploy-ops-uaa
  serial_groups: [ops-uaa]
  plan:
  - in_parallel:
    - get: uaa-config
      trigger: true
    - get: common
      trigger: true
    - get: terraform-yaml
    - get: stemcell-jammy
      trigger: true
    - get: uaa-release
      trigger: true
    - get: uaa-customized-release
      trigger: true
    - get: secureproxy-release
      trigger: true
  - put: uaa-deployment
    params:
      manifest: uaa-config/manifest.yml
      stemcells:
      - stemcell-jammy/*.tgz
      releases:
      - uaa-release/*.tgz
      - uaa-customized-release/*.tgz
      - secureproxy-release/*.tgz
      vars_files:
      - common/opsuaa.yml
      - terraform-yaml/state.yml
      ops_files:
      - uaa-config/ops/add-bpm.yml
      - uaa-config/ops/disk.yml
  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED to deploy ops UAA
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: '#cg-platform'
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: uaa-smoke-tests
  plan:
  - in_parallel:
    - get: pipeline-tasks
    - get: uaa-deployment
      trigger: true
  - task: smoke-tests
    file: pipeline-tasks/uaa-smoke-tests.yml
    params:
      BASE_URL: https://opslogin.fr.cloud.gov
  on_failure:
    put: slack
    params:
      text: |
        :x: UAA Smoke Tests for opslogin FAILED
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: '#cg-platform'
      username: ((slack-username))
      icon_url: ((slack-icon-url))

